name: Veracode Upload and Scan

on:
  workflow_dispatch:

jobs:
  veracode-sast-scan:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v2
        - name: check directory
          run: ls -la
        - name: Veracode Upload And Scan
          uses: veracode/veracode-uploadandscan-action@0.2.4
          with:
            # appname
            appname: VeraGHA-2.0
            # createprofile
            createprofile: true # default is true
            # filepath
            filepath: analysis/
            # version
            version:  ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}-${{ github.ref_name }} # default is Scan from Github job: ${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
            # vid
            vid: ${{secrets.VERACODE_API_ID}}
            # vkey
            vkey: ${{secrets.VERACODE_API_KEY}}
            # true or false
            #createsandbox: false # optional
            # name of the sandbox
            #sandboxname: # optional
            # wait X minutes for the scan to complete
            #scantimeout: # optional
            # modules to exclude from module selection
            #exclude: # optional
            # modules to include in module selection
            #include: # optional
            # business criticality - policy selection
            #criticality: # optional
            # filename pattern
            #pattern: # optional
            # replacement
            #replacement: # optional
            # specify to scan in a sandbox
            #sandboxid: # optional
            # All top level modules
            #scanallnonfataltoplevelmodules: # optional
            # platform selected modules
            #selected: # optional
            # selected modules like from previous scan
            #selectedpreviously: # optional
            # teams
            #teams: # optional
            # teams
            #toplevel: # optional
            # automatically delete the current scan if there are any errors when uploading files or starting the scan
            deleteincompletescan: 2 # optional
            # specify version of the Java API Wrapper; default is latest
            #javawrapperversion: # optional
            # show detailed diagnostic information, which you can use for debugging, in the output.
            debug: 1 # optional
    
